[package]
name = "rpu"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.37", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.29.0"
thiserror = "2.0.12"
