name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: make release VERSION=${{ github.ref_name }}
    - uses: softprops/action-gh-release@v2
      with:
        files: build/rpu-${{ github.ref_name }}.tgz
