name: Test & Release

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - run: make check
    - run: make release
    - uses: actions/upload-artifact@v4
      with:
        name: rpu
        path: target/release/rpu
